USE [master]
GO

/****** Object:  Database [MercanciasJyC]    Script Date: 22/09/2024 7:55:37 p. m. ******/
CREATE DATABASE [MercanciasJyC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MercanciasJyC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MercanciasJyC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MercanciasJyC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\MercanciasJyC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MercanciasJyC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MercanciasJyC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MercanciasJyC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MercanciasJyC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MercanciasJyC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MercanciasJyC] SET ARITHABORT OFF 
GO

ALTER DATABASE [MercanciasJyC] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MercanciasJyC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MercanciasJyC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MercanciasJyC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MercanciasJyC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MercanciasJyC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MercanciasJyC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MercanciasJyC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MercanciasJyC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MercanciasJyC] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MercanciasJyC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MercanciasJyC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MercanciasJyC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MercanciasJyC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MercanciasJyC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MercanciasJyC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MercanciasJyC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MercanciasJyC] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MercanciasJyC] SET  MULTI_USER 
GO

ALTER DATABASE [MercanciasJyC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MercanciasJyC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MercanciasJyC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MercanciasJyC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MercanciasJyC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MercanciasJyC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MercanciasJyC] SET QUERY_STORE = ON
GO

ALTER DATABASE [MercanciasJyC] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [MercanciasJyC] SET  READ_WRITE 
GO


